### ISSUE TITLE
current being drawn

### ISSUE THREAD

**Issue by vcmorini** [fochica/fochica-wiki#1]
Hello,
Thanks for your very cool tutorial.
Would you mind telling which current we can expect on the buzzer?

Many thanks!!

**Comment by ayavilevich** [comment]
Hey @vcmorini 
Are you referring to this tutorial: https://github.com/fochica/fochica-wiki/wiki/Passive-buzzer-guide ?
The current will depend on the in-series resistor with the buzzer. V = I * R.

**Comment by vcmorini** [comment]
Alright @ayavilevich :) 
I will consider the resistance of the buzzer then, from the datasheet, or measure it with multimeter. 
I was thinking about adding a potentiometer to the collector in order to control the volume. What is your opinion?
Many thanks and great tutorial, I appreciate it.

**Comment by ayavilevich** [comment]
A potentiometer will be great to control the volume.
